### ISSUE TITLE
Not an issue: hints on programming the SAM chip

### ISSUE THREAD

**Issue by mnantel** [arturo182/bbq10kbd_i2c_sw#2]
Arturo - I am a bit of a neophyte in relation with programming QFN chips. Any suggestions on how one can upload the code?

**Comment by arturo182** [comment]
You can use one of these cheap st-link clones off of Amazon, eBay or Aliexpress to reflash the SAMD
![image](https://user-images.githubusercontent.com/249082/91501942-1d8ae800-e8c7-11ea-8f68-c8191fde78bc.png)


On the HW, use the pins labeled CLK and IO, connect them to SWCLK and SWDIO on the st-link.
Then use the command `make stlink` in one terminal and `make flash` in another to flash the code onto the board.
